version: '3'
services:
    postgres:
        image: postgres:9.6.17
        environment: 
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: passme
        ports: 
            - "5432:5432"
    wildfly:
        image: jboss/wildfly:14.0.1.Final
        # build: .
        ports: 
            - "8080:8080"
            - "9990:9990"
    nginx:
        image: nginx:1.17.8
        build: .
        ports: 
            - "80:80"