= 3D-HTL-Leonding-Tag der offenen Tür - Auinger & Tripić - 5BHIF 2019/2020
Philipp Auinger <philipp-auinger@gmx.at>, Nenad Tripić  <tripicnenad@hotmail.com>
v1.0, 2020-04-20
:toc:
:toc-title: Inhaltsverzeichnis
:toclevels: 3
:sectnums:

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

=== Pflichtenheft
Das Pflichtenheft finden Sie als https://philippauinger.github.io/htl-leonding-3D-tadeot/Pflichtenheft/Pflichtenheft.html[Website], link:Pflichtenheft/Pflichtenheft.adoc[adoc] oder link:Pflichtenheft/Pflichtenheft.pdf[PDF]

=== Wo ist das Programm gehostet?
Diese Applikation finden Sie auf http://vm85.htl-leonding.ac.at/tadeot/

=== Worum handelt dieses Projekt?
Diese Projekt wurde extra für den Tag der offenen Tür kreiert. Es ist ein Derivat von https://github.com/philippAuinger/htl-leonding-3D-base[Base] und erweitert es um diverse Funktionen. Beispiele für solche Erweiterungen sind:

* Suche nach Austellungstücken
* Anzeigen von Abteilungen
* Anzeigen von Wegen zum Stand
* ...

Mehr Informationen entnehmen Sie bitte dem https://philippauinger.github.io/htl-leonding-3D-tadeot/Pflichtenheft/Pflichtenheft.html[Pflichtenheft]


=== Wie starte ich das Projekt?
TIP: Am einfachsten lässt sich das Projekt mit dem Shell-Skript ausführen. (Hinweis: Abhängig vom Betriebssystem können die Zeilenendsequenzen Probleme machen. Im Regelfall aber nicht!)

Die ganze Applikation mit allen benötigten Komponenten wird gedockert und im Repository zur Verfügung gestellt. Dabei wird beim `docker-compose up` oder beim Ausführen des link:lokal_testen.sh[Shell-Skriptes] folgendes gemacht:

. *NGINX* container erstellt und der link:Application[Application-Ordner] mit der ganzen Logik auf den NGINX deployed
. *Postgres* container erstellt mit den Zugangsdaten `POSTGRES_USER: postgres` `POSTGRES_PASSWORD: passme`
. *Wildfly* container erstellt und link:Tadeot.war[] deployed

Das Ergebnis kann dann auf http://localhost:80 oder auf http://{DockerIP-Adresse}:80 begutachtet werden.

=== Wie fuktioniert dieses Programm?
Ein Application Server, in diesem Falle ein Wildfly, liest eine CSV-Datei ein von Ausstellungsstücken (link:Tadeot/src/main/resources/META-INF/exhibits.csv[exhibits.csv]) und persitiert die Daten in die Postgres Datenbank. Gleichzeitig stellt der Wildfly die Daten über eine http://vm85.htl-leonding.ac.at:8080/Tadeot/api/exhibit[API] zur Verfügung. Per JavaScript wird dann auf diese Schnittstelle zugegriffen und im Programm als Liste von Ausstellungsstücken dargestellt. Der HTML-Code und JavaScript wird auf den NGINX deployed und somit die ganze Applikation zugänglich gemacht.